//
//  SettingsPresenter.swift
//  MyMapProject
//
//  Created by Enes Kılıç on 31.10.2021.
//  Copyright (c) 2021 Enes Kılıç. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func presentSomething(response: Settings.Something.Response)
    func presentShowDistanceCell(with labelText: String, currentSwitchValue: Bool)
}

class SettingsPresenter: SettingsPresentationLogic {
    
    weak var viewController: SettingsDisplayLogic?

    // MARK: Parse and calc respnse from SettingsInteractor and send simple view model to SettingsViewController to be displayed

    func presentSomething(response: Settings.Something.Response) {
        let viewModel = Settings.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentShowDistanceCell(with labelText: String, currentSwitchValue: Bool) {
        
    }
    
//
//    func presentSomethingElse(response: Settings.SomethingElse.Response) {
//        let viewModel = Settings.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
